comp_channel_map1 = {
  'EEG-Fz': 'Fz',
  'EEG-0':  'FC3',
  'EEG-1':  'FC1',
  'EEG-2':  'FCz',
  'EEG-3':  'FC2',
  'EEG-4':  'FC4',
  'EEG-5':  'C5',
  'EEG-C3': 'C3',
  'EEG-6':  'C1',
  'EEG-Cz': 'Cz',
  'EEG-7':  'C2',
  'EEG-C4': 'C4',
  'EEG-8':  'C6',
  'EEG-9':  'CP5',
  'EEG-10': 'CP3',
  'EEG-11': 'CPz',
  'EEG-12': 'CP4',
  'EEG-13': 'CP6',
  'EEG-14': 'P3',
  'EEG-Pz': 'Pz',
  'EEG-15': 'P4',
  'EEG-16': 'POz',
  'EOG-left':'EOG-left',
  'EOG-central':'EOG-central',
  'EOG-right':'EOG-right'
}

comp_channel_map2 = {
  'EEG-Fz': 'Fz',
  'EEG-0':  'FC5',
  'EEG-1':  'FC1',
  'EEG-2':  'FCz',
  'EEG-3':  'FC2',
  'EEG-4':  'FC6',
  'EEG-5':  'T7',
  'EEG-C3': 'C3',
  'EEG-6':  'C1',
  'EEG-Cz': 'Cz',
  'EEG-7':  'C2',
  'EEG-C4': 'C4',
  'EEG-8':  'T8',
  'EEG-9':  'CP5',
  'EEG-10': 'CP1',
  'EEG-11': 'CPz',
  'EEG-12': 'CP2',
  'EEG-13': 'CP6',
  'EEG-14': 'P3',
  'EEG-Pz': 'Pz',
  'EEG-15': 'P4',
  'EEG-16': 'POz',
  'EOG-left':'EOG-left',
  'EOG-central':'EOG-central',
  'EOG-right':'EOG-right'
}

comp_channel_map3 = {
  'EEG-Fz': 'Fz',
  'EEG-0':  'FC3',
  'EEG-1':  'FC1',
  'EEG-3':  'FC2',
  'EEG-4':  'FC4',
  'EEG-5':  'C5',
  'EEG-C3': 'C3',
  'EEG-6':  'C1',
  'EEG-Cz': 'Cz',
  'EEG-7':  'C2',
  'EEG-C4': 'C4',
  'EEG-8':  'C6',
  'EEG-9':  'CP3',
  'EEG-10': 'CP1',
  'EEG-11': 'CPz',
  'EEG-12': 'CP2',
  'EEG-13': 'CP4',
  'EEG-14': 'P1',
  'EEG-Pz': 'Pz',
  'EEG-15': 'P2',
  'EEG-16': 'POz',
  'EOG-left':'EOG-left',
  'EOG-central':'EOG-central',
  'EOG-right':'EOG-right'
}
